### ISSUE TITLE
Range setting don't work [v2.0.0]

### ISSUE THREAD

**Issue by xgbcman** [gruijter/com.gruijter.virtualradar#1]
Range setting is locked to 5 km and don't affect distance to aircrafts. When I try to change range setting i get error message "Setting could not be saved (Invalid_device). The 5 km range picks up aircrafts far away, the range is far more than 5 km.

**Comment by gruijter** [comment]
This is caused by the latest app update where I added some device settings. This causes an incompatibility with already paired devices in Homey. Try to delete the app, and re-install. It should then work correctly.

**Comment by xgbcman** [comment]
Works like a charm :)
