### ISSUE TITLE
Can't use tags in flows anymore

### ISSUE THREAD

**Issue by sj3fk3** [gruijter/com.gruijter.virtualradar#5]
Ever since the upgrade to homey 2, the flows that always used to work, don't work anymore. New flows also won't work. I think there might be something different with escaping the tags or something? 

Triggers work just fine. I want to announce planes above/near our house. When I drag in a tag from virtual radar the flow stops working. Other tags do work..

**Comment by Rene62** [comment]
I have the same problem. I supose its related to V2. I hope you can fix it, i miss a lot of planes :-)

**Comment by gruijter** [comment]
That is do weird. I tested myself with Homey V2 for a few weeks now, and I have no problem triggering when a plane is coming in range, and using some tags to notify me. Can you provide the app logs? Also please include how your flow is built. Maybe you are using different tags then me? Or you use the tags in combination with other app flowcards?

![Screenshot_20190314-210009](https://user-images.githubusercontent.com/19174120/54387957-f02f8780-469c-11e9-8ba5-ccb3f1efd15b.png)

**Comment by gruijter** [comment]
@sj3fk3 @Rene62 any news from your side? On my Homey all works well.

**Comment by sj3fk3** [comment]
I still can not get msg from virtualradar to mqtt, but the tags do work if I (directly) send them to say Google voice. So I do think there is something wonky in the capsulation or something?

**Comment by gruijter** [comment]
Maybe it is a problem with the mqtt app? Which app are you using? Mqtt client? And how do you use the virtual radar tags with the mqtt app? Can you post an example flow that doesnt work?

**Comment by gruijter** [comment]
Any update from your side?

**Comment by Rene62** [comment]
Hi, Sorry for the late response.
I had to remove and install the app and restart homey a few times to get it working again :-).
(I had some more issues with homey, so i think homey was the problem.)

**Comment by gruijter** [comment]
Ok, no problem. I'll close the issue then.

**Comment by gruijter** [comment]
Hi @sj3fk3 @Rene62,

I found a bug on flow.athom.com that is likely to be related to the issue you are experiencing.

The tags get an additional space, resulting in the flows not working. I already made a bug report with athom for this. But in the mean time its better to create flows from your mobile app.
