### ISSUE TITLE
New adsbexchange api - error 403

### ISSUE THREAD

**Issue by gruijter** [gruijter/com.gruijter.virtualradar#6]
https://github.com/TwinFan/LiveTraffic/issues/132

**Comment by gruijter** [comment]
Alternative data source? 
https://opensky-network.org/apidoc/rest.html

**Comment by C0kedk** [comment]
Opensky is only free alternative i could find, realtraffic is also paid...

So yes please change source to Opensky 🙂

**Comment by gruijter** [comment]
Thx for checking. I'm also in contact with adsbexchange to see if Homey users can keep access.

**Comment by C0kedk** [comment]
More on the subject here
https://forums.x-plane.org/index.php?/forums/topic/178284-ads-b-exchange-rules-for-access-after-25-apr-2019/

**Comment by gruijter** [comment]
I will try to find some time to look at opensky this weekend. But the api is limited compared to adsbexchange, so not all functionality can be achieved.

I hope I get a response from adsbexchange soon. The creator has a problem with the number of api calls that will come in from Homey users, but I'm still 'negotiating' with him :)

**Comment by C0kedk** [comment]
Lets hope you can sweet talk him 😉

**Comment by gruijter** [comment]
I started working on switching to opensky. But it is much more work then I though. I need to completely rewrite my app to make it flexible for switching data source. So please be (very) patient for a solution...

**Comment by C0kedk** [comment]
Any news..?

**Comment by gruijter** [comment]
yes, but not so good news.

Opensky provides very limited information in their api. No from or to airport, no operator, no aircraft make and model. Also the information they do provide (location, speed, height, direction) is often incorrect, making it not very useful.

ADSB-exchange informed me (after a lot of emails) that they are not willing to provide their api free of charge to Homey users. They have a free option for 'feeders', so I started by building a adsb receiver myself and am now a feeder. This gives me personal access, but I cannot share this with Homey app user obviously. Secondly, they changed their api so also their information is somewhat reduced, but at least it is accurate.

The best option left seems to be the paid api that adsb-exchange is providing for non-feeders. But I'm not sure if that is worth the effort I have to put in.

**Comment by gruijter** [comment]
please visit and comment on the forum: https://community.athom.com/t/14605

**Comment by gruijter** [comment]
Fixed in v3
