### ISSUE TITLE
Krijg Virtual Radar niet aan de praat...

### ISSUE THREAD

**Issue by JukkaVdB** [gruijter/com.gruijter.virtualradar#7]
Hey Robin,

Ik krijg de app niet aan de praat.  Ik heb vooral interesse in het gedeelte “Radar”.  Heb je toevallig geen handleiding voor dummies? :-)

**Comment by gruijter** [comment]
um, ik heb het net weer eens geprobeerd en een radar zonder probleem toegevoegd (openSky). Wel heb ik de range van de radar even op 100km gezet (na pairen naar device settings gaan), want er wordt in corona tijd niet zoveel gevlogen in de buurt :)

wat werkt er niet bij jou?

**Comment by JukkaVdB** [comment]
Het is me uiteindelijk gelukt, maar ik dacht dat ik een notificatie kon krijgen met welk vliegtuig er nu net over mijn huis komt... :-)

Met vriendelijke groeten,

Van den Bulcke Jukka


Van den Bulcke Jukka
Swaenebeecklaan 24
2970 's-Gravenwezel 
+32 475 800 456
jukka@telenet.be

**Comment by gruijter** [comment]
tuurlijk kun je een notificatie krijgen. Maak gewoon een flow daarvoor....

**Comment by JukkaVdB** [comment]
En welke flow moet ik dan gebruiken om een notificatie te krijgen om te weten te komen welk vliegtuig er over vliegt aub?

Met vriendelijke groeten,

Van den Bulcke Jukka


Van den Bulcke Jukka
Swaenebeecklaan 24
2970 's-Gravenwezel 
+32 475 800 456
jukka@telenet.be

**Comment by gruijter** [comment]
Voor support hoe Homey (of de app) te gebruiken kun je het beste naar het gebruikersforum: 

https://community.athom.com/t/14605
