### ISSUE TITLE
Homey App

### ISSUE THREAD

**Issue by JukkaVdB** [gruijter/com.gruijter.virtualradar#8]
Hi, how van I make a flow in Homey to know when a plane is flying over my house?

Greetings,
Van den Bulcke Jukka

**Comment by gruijter** [comment]
Hi Jukka,

Best to ask for flow support on the forum:
https://community.athom.com/t/14605

**Comment by ECort** [comment]
Hi Jukka,
I'm very much busy with this. Use 'Viruele Radar'. 

- https://homey.app/nl-nl/app/com.gruijter.virtualradar/Virtuele-Radar/
- During installation app you need to register for the 'opensky' api. Little bit difficult but do-able. Opensky not as complete as Flight Radar24 but deliveres alle major flights.
- App knows your HOMEY location and starts counting wihtin 5km radius
- dashboard shows flights
- I created a 'logic' variables. 1 keeps counting 'total' and 1 sets total per day on 23:59. Substracting the 2 gives 'total / day'

Works fine but experiencing littel robustness issues when exactly counting number of flights overhead. Somewehere 'entering or leaving' planes are sometimes missed. Robin Gruijter is helping me out. 

Good luck. With all thes planes overhead it will certainly give you good insights.

**Comment by gruijter** [comment]
Hi @ECort maybe you can share your counting flows and screenshots of that on the forum. Would be helpful to everyone I think!
